name: Install pnpm and setup Node.js
description: Composite action to install pnpm and setup Node.js used in several workflows

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/setup@a0881977cd8ea73b1ed212236c99ca10dcc80cf4 # v3.1.1
      with:
        version: 12
        runtime: node@lts
