name: Check exports

on: pull_request

jobs:
  quality:
    name: Check exports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install TypeScript
        run: pnpm add typescript
      - name: Install @arethetypeswrong/cli
        run: pnpm add @arethetypeswrong/cli
      - name: Run check-exports
        run: pnpm check-exports