name: Check exports

on: pull_request

jobs:
  check-exports:
    name: Check exports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm and setup Node.js
        uses: ./.github/actions/pnpm-node
      - name: Install TypeScript
        run: pnpm add typescript
      - name: Install @arethetypeswrong/cli
        run: pnpm add @arethetypeswrong/cli
      - name: Run check-exports
        run: pnpm check-exports