name: Commitlint

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commitlint:
    name: Check commits with commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Install pnpm and setup Node.js
        uses: ./.github/actions/pnpm-node
      - name: Install commitlint
        run: |
          pnpm add conventional-changelog-conventionalcommits
          pnpm add commitlint@latest
      - name: Validate PR commits with commitlint
        run: pnpx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
