name: Commitlint

on: pull_request

jobs:
  commitlint:
    name: Check commits with commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install commitlint
        run: |
          pnpm add conventional-changelog-conventionalcommits
          pnpm add commitlint@latest
      - name: Validate PR commits with commitlint
        run: pnpx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
