name: Run tests

on: pull_request

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm and setup Node.js
        uses: ./.github/actions/pnpm-node
      - name: Install TypeScript
        run: pnpm add typescript
      - name: Install Vitest
        run: pnpm add vitest
      - name: Run Vitest
        run: pnpm test