name: Run tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install pnpm and setup Node.js
        uses: ./.github/actions/pnpm-node
      - name: Install TypeScript
        run: pnpm add typescript
      - name: Install Vitest
        run: pnpm add vitest
      - name: Run Vitest
        run: pnpm test